### ISSUE TITLE
Implement uncheck() and unchecked() for ThrowingBinaryOperator

### ISSUE THREAD

**Issue by pivovarit** [TouK/ThrowingFunction#13]

**Comment by brunoabdon** [comment]
Does it does the trick? 

If I understood correctly, what would be the `uncheck()` method in `ThrowingBiFunction` is actually called `unchecked()`, so I kept it as that.

**Comment by pivovarit** [comment]
Yes, it's fine :)
Please add a testcase for this and we are ready to go

**Comment by pivovarit** [comment]
Thanks for your contribution. I am now offline most of the time and I will get back to you soon in few days. Cheers!

**Comment by brunoabdon** [comment]
This can be closed.
