### ISSUE TITLE
Immediete evaluation of throwing blocks

### ISSUE THREAD

**Issue by Tarrasch** [TouK/ThrowingFunction#16]
So I usually find myself within this situation:

![selection_019](https://cloud.githubusercontent.com/assets/294349/14339448/d655e3c2-fca8-11e5-8388-14412ff4fb6e.png)

```java
    public static void main(String[] args) {
        int num = readIntFromFile();
    }

    private static Integer readIntFromFile() throws Exception {
        return 4;
    }
```

So let's see what we can do with the line:

```java
int num = readIntFromFile();
```

How can this library help me? Best I've found is:

```java
int num = ThrowingSupplier.unchecked(Helpers::readIntFromFile).get();
```

Would it make sense to implement a method like `uncheckedGet`:

```java
int num = ThrowingSupplier.uncheckedGet(() -> readIntFromFile());
```

or

```java
int num = ThrowingSupplier.uncheckedGet(Helpers::readIntFromFile);
```

Here's a [scratchpad](https://gist.github.com/Tarrasch/a817b1449bfcc5e3653b0bdbccdfec62) I have experimented with.

-------

So, is a function like `uncheckedGet` worth having? Regardless I hope this was issue was an interesting read.

**Comment by pivovarit** [comment]
Well, this library was clearly designed for something else. It was designed for seamless blending checked lambdas with java.util.function standard functional types and you just want to rethrow your checked exception as RuntimeException, but I will look more into this tomorrow. Thanks :)

**Comment by Tarrasch** [comment]
Cool. I saw this package as a somewhat academic solution to the checked-exception handling hell that's omnipresent in java. But maybe there's a deeper meaning I haven't seen yet. :)

Afaik, any solution to checked-exception handling has to wrap expressions like `readFromFile()` into unevaluated expressions `() -> readFromFile()` (nothing special to Java 8, except the convenient syntax).

Now the examples in your readme seem to specialize to non-anonymous functions like `URI::new`. But from a functional programmers mindset they are equivalent to `x -> URI.new(x)`.

**Comment by pivovarit** [comment]
This is just for dealing with Java8 exceptions in lambdas and works only with version of 8 and beyond.
If a checked exception appears in your lambdas, it ruins everything because java.util.function functional types do not have any `throws` clause. It could be useful in your case, but it was designed for something else.

btw, method references in Java8 are just syntactic sugar over regular anonymous functions like this `x -> URI.new(x)`

Consider this part of JDK8 documentation:

> You use lambda expressions to create anonymous methods. Sometimes, however, a lambda expression does nothing but call an existing method. In those cases, it's often clearer to refer to the existing method by name. Method references enable you to do this; they are compact, easy-to-read lambda expressions for methods that already have a name.
